cp ../samtools/bam.h  ./
cp ../bam/BamIndex.h  ./
cp ../bam/BamInterface.h  ./
cp ../general/BaseAsciiMap.h  ./
cp ../fastq/BaseComposition.h  ./
cp ../fastq/BaseCount.h  ./
cp ../general/BaseQualityHelper.h  ./
cp ../general/BaseUtilities.h  ./
cp ../general/BasicHash.h  ./
cp ../general/BgzfFileType.h  ./
cp ../general/BgzfFileTypeRecovery.h  ./
cp ../samtools/bgzf.h  ./
cp ../general/CharBuffer.h  ./
cp ../general/Chromosome.h  ./
cp ../general/Cigar.h  ./
cp ../bam/CigarHelper.h  ./
cp ../general/CigarRoller.h  ./
cp ../general/Constant.h  ./
cp ../general/CSG_MD5.h  ./
cp ../general/Error.h  ./
cp ../general/ErrorHandler.h  ./
cp ../fastq/FastQFile.h  ./
cp ../fastq/FastQStatus.h  ./
cp ../general/FileType.h  ./
cp ../general/FortranFormat.h  ./
cp ../general/Generic.h  ./
cp ../bam/GenericSamInterface.h  ./
cp ../general/GenomeSequence.h  ./
cp ../general/GenomeSequenceHelpers.h  ./
cp ../general/GenotypeLists.h  ./
cp ../glf/GlfException.h  ./
cp ../glf/GlfFile.h  ./
cp ../general/glfHandler.h  ./
cp ../glf/GlfHeader.h  ./
cp ../glf/GlfRecord.h  ./
cp ../glf/GlfRefSection.h  ./
cp ../glf/GlfStatus.h  ./
cp ../general/GreedyTupleAligner.h  ./
cp ../general/GzipFileType.h  ./
cp ../general/GzipHeader.h  ./
cp ../general/Hash.h  ./
cp ../general/IndexBase.h  ./
cp ../general/InplaceMerge.h  ./
cp ../general/InputFile.h  ./
cp ../general/Input.h  ./
cp ../general/IntArray.h  ./
cp ../general/IntHash.h  ./
cp ../samtools/khash.h  ./
cp ../samtools/knetfile.h  ./
cp ../general/LongHash.h  ./
cp ../general/LongInt.h  ./
cp ../general/LongLongCounter.h  ./
cp ../general/MapFunction.h  ./
cp ../general/MathConstant.h  ./
cp ../general/MathMatrix.h  ./
cp ../general/MathVector.h  ./
cp ../general/MemoryAllocators.h  ./
cp ../general/MemoryInfo.h  ./
cp ../general/MemoryMapArray.h  ./
cp ../general/MemoryMap.h  ./
cp ../general/MiniDeflate.h  ./
cp ../general/NonOverlapRegions.h  ./
cp ../general/PackedVector.h  ./
cp ../general/Parameters.h  ./
cp ../general/PedigreeAlleleFreq.h  ./
cp ../general/PedigreeAlleles.h  ./
cp ../general/PedigreeDescription.h  ./
cp ../general/PedigreeFamily.h  ./
cp ../general/PedigreeGlobals.h  ./
cp ../general/Pedigree.h  ./
cp ../general/PedigreePerson.h  ./
cp ../general/Performance.h  ./
cp ../general/PhoneHome.h  ./
cp ../bam/PileupElementBaseQual.h  ./
cp ../bam/PileupElement.h  ./
cp ../bam/Pileup.h  ./
cp ../bam/PosList.h  ./
cp ../general/QuickIndex.h  ./
cp ../general/Random.h  ./
cp ../general/ReferenceSequence.h  ./
cp ../general/ReusableVector.h  ./
cp ../bam/SamCoordOutput.h  ./
cp ../bam/SamFile.h  ./
cp ../bam/SamFileHeader.h  ./
cp ../bam/SamFilter.h  ./
cp ../bam/SamFlag.h  ./
cp ../bam/SamHeaderHD.h  ./
cp ../bam/SamHeaderPG.h  ./
cp ../bam/SamHeaderRecord.h  ./
cp ../bam/SamHeaderRG.h  ./
cp ../bam/SamHeaderSQ.h  ./
cp ../bam/SamHeaderTag.h  ./
cp ../bam/SamHelper.h  ./
cp ../bam/SamInterface.h  ./
cp ../bam/SamQuerySeqWithRefHelper.h  ./
cp ../bam/SamRecord.h  ./
cp ../bam/SamRecordHelper.h  ./
cp ../bam/SamRecordPool.h  ./
cp ../bam/SamReferenceInfo.h  ./
cp ../bam/SamStatistics.h  ./
cp ../bam/SamStatus.h  ./
cp ../bam/SamTags.h  ./
cp ../bam/SamValidation.h  ./
cp ../general/SimpleStats.h  ./
cp ../general/SmithWaterman.h  ./
cp ../general/Sort.h  ./
cp ../general/StatGenStatus.h  ./
cp ../general/STLUtilities.h  ./
cp ../general/StringAlias.h  ./
cp ../general/StringArray.h  ./
cp ../general/StringBasics.h  ./
cp ../general/StringHash.h  ./
cp ../general/StringMap.h  ./
cp ../general/Tabix.h  ./

cp ../general/TrimSequence.h  ./
cp ../general/UncompressedFileType.h  ./
cp ../general/UnitTest.h  ./
cp ../vcf/VcfFile.h  ./
cp ../vcf/VcfFileReader.h  ./
cp ../vcf/VcfFileWriter.h  ./
cp ../vcf/VcfGenotypeField.h  ./
cp ../vcf/VcfGenotypeFormat.h  ./
cp ../vcf/VcfGenotypeSample.h  ./
cp ../vcf/VcfHeader.h  ./
cp ../vcf/VcfHelper.h  ./
cp ../vcf/VcfRecordDiscardRules.h  ./
cp ../vcf/VcfRecordField.h  ./
cp ../vcf/VcfRecordFilter.h  ./
cp ../vcf/VcfRecordGenotype.h  ./
cp ../vcf/VcfRecord.h  ./
cp ../vcf/VcfRecordInfo.h  ./
cp ../vcf/VcfSubsetSamples.h  ./
