pipelinePath=".."

## Clean previous files generated by previous runs
rm -rf logs tmp  snp laser jobfiles  seekin  run.yaml


## Generate the job files in the directory "./jobfiles" 
python  $pipelinePath/lib/GetConf.py -c example.conf -o run.yaml

## Run the piepline using snakemake 
## The snake command below is customized to USG or PBS Pro cluster. 

snakemake --snakefile null --unlock
snakemake -s $pipelinePath/Snakefile --jobs 300 --rerun-incomplete --timestamp --printshellcmds --stats logs/snakemake.stats --configfile run.yaml --latency-wait 60 --cluster-config cluster.yaml --drmaa " -pe OpenMP {threads} -l mem_free={cluster.mem} -l h_rt={cluster.time} -cwd -v PATH -e logs -o logs -w n" --jobname "SEEKIN.slave.{rulename}.{jobid}.sh" --config ANALYSIS_ID=2017-08-11T00-07-13.131971 >> logs/snakemake.log 2>&1

# You can also run step varCall, laser separately using the "target"  option in snakemake 
# For calling variants only, please add option "varCall" to the above pipeline. E.g. snakemake -s $pipelinePath/Snakefile varCall ...
# For running laser only, please add option "laser" to the above pipeline. E.g. snakemake -s $pipelinePath/Snakefile laser ...

